# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

movementfunc_cpp <- function(AGE, MONTH, MaxCell, AdultMove, YearlyTotal) {
    .Call(`_TwinFish_movementfunc_cpp`, AGE, MONTH, MaxCell, AdultMove, YearlyTotal)
}

mortalityfunc_cpp <- function(AGE, MaxCell, MONTH, YEAR, NatMort, Weight, Selectivity, YearlyTotal, Effort) {
    .Call(`_TwinFish_mortalityfunc_cpp`, AGE, MaxCell, MONTH, YEAR, NatMort, Weight, Selectivity, YearlyTotal, Effort)
}

recruitmentfunc_cpp <- function(MaxCell, MaxAge, BHa, BHb, PF, Mature, Weight, Settlement, YearlyTotal) {
    .Call(`_TwinFish_recruitmentfunc_cpp`, MaxCell, MaxAge, BHa, BHb, PF, Mature, Weight, Settlement, YearlyTotal)
}

RunModelfunc_cpp <- function(YEAR, MaxAge, MaxYear, MaxCell, NatMort, BHa, BHb, PF, AdultMove, Mature, Weight, Settlement, YearlyTotal, Select, Effort) {
    .Call(`_TwinFish_RunModelfunc_cpp`, YEAR, MaxAge, MaxYear, MaxCell, NatMort, BHa, BHb, PF, AdultMove, Mature, Weight, Settlement, YearlyTotal, Select, Effort)
}

rcpparma_hello_world <- function() {
    .Call(`_TwinFish_rcpparma_hello_world`)
}

rcpparma_outerproduct <- function(x) {
    .Call(`_TwinFish_rcpparma_outerproduct`, x)
}

rcpparma_innerproduct <- function(x) {
    .Call(`_TwinFish_rcpparma_innerproduct`, x)
}

rcpparma_bothproducts <- function(x) {
    .Call(`_TwinFish_rcpparma_bothproducts`, x)
}

